sudo: false

language: python

env:
    matrix:
        - PYTHON_VERSION=2.7
        - PYTHON_VERSION=3.5

install:
    - source .ci/travis.sh

script: |
    if [[ "$PYTHON_VERSION" == "2.7" ]] && [ -n "$GITHUB_API_KEY" ]; then
        source .ci/upload-paper.sh
    fi

